export const CHANGE_TITLE_FIELD = 'CHANGE_TITLE_FIELD';
export const CHANGE_COMPOSER_FIELD = 'CHANGE_COMPOSER_FIELD';
export const CHANGE_INSTRUMENTATION_FIELD = 'CHANGE_INSTRUMENTATION_FIELD';
export const UPLOAD_MUSIC_SCORE = 'UPLOAD_MUSIC_SCORE';
export const UPDATE_CURRENT_USER_SCORES = 'UPDATE_CURRENT_USER_SCORES';
export const REMOVE_SCORE_FROM_USER_SCORES = 'REMOVE_SCORE_FROM_USER_SCORES';
export const REMOVE_COMMENT_FROM_USER_COMMENTS = 'REMOVE_COMMENT_FROM_USER_COMMENTS';

export const VIEW_SCORE_TOGGLE = 'VIEW_SCORE_TOGGLE';
export const VIEW_VIDEOS_TOGGLE = 'VIEW_VIDEOS_TOGGLE';
export const VIEW_COMMENTS_TOGGLE = 'VIEW_COMMENTS_TOGGLE';
export const MUSIC_UPLOAD_FORM_TOGGLE = 'MUSIC_UPLOAD_FORM_TOGGLE';
export const CLICKED_SCORE = 'CLICKED_SCORE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const SELECTED_DATE = 'SELECTED_DATE';
export const DISPLAY_EVENT_FORM = 'DISPLAY_EVENT_FORM';
export const HANDLE_EVENT_TITLE_CHANGE = 'HANDLE_EVENT_TITLE_CHANGE';
export const HANDLE_EVENT_DESCRIPTION_CHANGE = 'HANDLE_EVENT_DESCRIPTION_CHANGE';
export const HANDLE_EVENT_DATE_CHANGE = 'HANDLE_EVENT_DATE_CHANGE';
export const HANDLE_EVENT_START_TIME_CHANGE = 'HANDLE_EVENT_START_TIME_CHANGE';
export const HANDLE_EVENT_END_TIME_CHANGE = 'HANDLE_EVENT_END_TIME_CHANGE';
export const GET_CURRENT_USER_EVENTS = 'GET_CURRENT_USER_EVENTS';
export const REMOVE_EVENT_FROM_USER_EVENTS = 'REMOVE_EVENT_FROM_USER_EVENTS';
export const CHANGE_COMMENT_MEASURE_FIELD = 'CHANGE_COMMENT_MEASURE_FIELD';
export const CHANGE_COMMENT_DESCRIPTION_FIELD = 'CHANGE_COMMENT_DESCRIPTION_FIELD';
export const GET_SCORE_COMMENTS = 'GET_SCORE_COMMENTS';
export const CLEAR_COMMENT_FORM_FIELDS = 'CLEAR_COMMENT_FORM_FIELDS';

export const ADD_NEW_COMMENT_TO_SCORE = 'ADD_NEW_COMMENT_TO_SCORE'

export const ADD_NEW_MUSIC_SCORE = 'ADD_NEW_MUSIC_SCORE'
export const ADD_NEW_EVENT = 'ADD_NEW_EVENT'
