export const CHANGE_TITLE_FIELD = 'CHANGE_TITLE_FIELD';
export const CHANGE_COMPOSER_FIELD = 'CHANGE_COMPOSER_FIELD';
export const UPLOAD_MUSIC_SCORE = 'UPLOAD_MUSIC_SCORE';
export const UPDATE_CURRENT_USER_SCORES = 'UPDATE_CURRENT_USER_SCORES';
