export const CHANGE_TITLE_FIELD = 'CHANGE_TITLE_FIELD';
export const CHANGE_COMPOSER_FIELD = 'CHANGE_COMPOSER_FIELD';
export const CHANGE_INSTRUMENTATION_FIELD = 'CHANGE_INSTRUMENTATION_FIELD';

export const UPLOAD_MUSIC_SCORE = 'UPLOAD_MUSIC_SCORE';
export const UPDATE_CURRENT_USER_SCORES = 'UPDATE_CURRENT_USER_SCORES';
export const REMOVE_SCORE_FROM_USER_SCORES = 'REMOVE_SCORE_FROM_USER_SCORES';
export const VIEW_SCORE_TOGGLE = 'VIEW_SCORE_TOGGLE';
export const CLICKED_SCORE = 'CLICKED_SCORE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
